[versions]
kotlin = "2.2.21"
material = "1.13.0"
okhttp = "5.3.2"
oss-license = "17.3.0"
appcompat = "1.7.1"
room = "2.8.4"
json = "20250517"
junit = "4.13.2"
truth = "1.4.5"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
coroutines = "1.10.2"
lifecycle = "2.10.0"
koin = "4.1.1"
composeBom = "2025.11.00"
compose-activity = "1.12.0"
compose-viewmodel = "2.9.4"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0-rc01"
material3AdaptiveNav3 = "1.3.0-alpha04"
datastorePreferences = "1.2.0"
kotlinSerializationJson = "1.9.0"

# Plugin versions
agp = "8.13.1"
ksp = "2.3.2"
oss-license-plugin = "0.10.9" # Also update in settings.gradle.kts



[libraries]
# Kotlin Std libs
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

# Jetpack Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui-material = { group = "androidx.compose.material3", name = "material3" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling-debug = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-activity = { group = "androidx.activity", name= "activity-compose", version.ref = "compose-activity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }

# Navigation 3
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

# Core Dependency
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
oss-license = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "oss-license" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# DataStore Preference
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

# Room
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Networking
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Android Lifecycle
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Dependency Injection
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

# Json
json = { group = "org.json", name = "json", version.ref = "json" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }



[bundles]
# Jetpack Compose Dependencies
compose = ["compose-ui-material", "compose-ui-preview", "compose-activity", "compose-viewmodel"]
compose-debug = ["compose-ui-tooling-debug"]

# Navigation 3 Dependencies
navigation3 = ["androidx-navigation3-runtime", "androidx-navigation3-ui", "androidx-lifecycle-viewmodel-navigation3", "androidx-material3-adaptive-navigation3"]

# Android Architecture Releated Components
room = ["room-ktx", "room-testing"]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]

# DataStore Preference
datastore-preferences = ["androidx-datastore-preferences", "kotlinx-serialization-json"]

# Coroutines Dependencies
coroutines = ["coroutines-core", "coroutines-android"]
coroutines-test = ["coroutines-core", "coroutines-test"]

# Dependency Injection Dependencies
koin = ["koin", "koin-compose"]

# General Test Dependencies
unit-test = ["junit", "truth"]
android-test = ["androidx-test-ext-junit", "espresso-core"]



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "oss-license-plugin" }
