[versions]
# Library versions
coreKtx = "1.17.0"
material = "1.13.0"
okhttp = "5.3.2"
oss-license = "17.3.0"
appcompat = "1.7.1"
room = "2.8.4"
json = "20250517"
junit = "4.13.2"
truth = "1.4.5"
androidx-test-ext-junit = "1.3.0"
coroutines = "1.10.2"
lifecycle = "2.10.0"
koin = "4.1.1"
composeBom = "2025.12.00"
compose-activity = "1.12.1"
compose-viewmodel = "2.10.0"
datastorePreferences = "1.2.0"
kotlinSerializationJson = "1.9.0"

# Plugin versions
agp = "8.13.1"
ksp = "2.3.3"
kotlin = "2.2.21"
oss-license-plugin = "0.10.9" # Also update in settings.gradle.kts






[libraries]
# Jetpack Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui-material = { module = "androidx.compose.material3:material3" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling-debug = { module = "androidx.compose.ui:ui-tooling" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }

# Core Dependency
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
oss-license = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "oss-license" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# DataStore Preference
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

# Room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

# Networking
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Android Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Dependency Injection
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Json
json = { module = "org.json:json", version.ref = "json" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }






[bundles]
# Jetpack Compose Dependencies
compose = ["compose-ui-material", "compose-ui-preview", "compose-activity", "compose-viewmodel"]
compose-debug = ["compose-ui-tooling-debug"]

# Coroutines Dependencies
coroutines = ["coroutines-core", "coroutines-android"]

# General Test Dependencies
unit-test = ["junit", "truth"]






[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "oss-license-plugin" }
